# Site settings
title: "ZAIRIG Imad Cv"
description: "Digital Resume hosted in Github."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "ZAIRIG Imad"
resume_title:                   "Symfony Certified Developer | AWS Certified Developer ☁"
resume_contact_email:           "imadzairig@gmail.com"
resume_contact_telephone:       "----"
resume_contact_address:         "Paris ,France"
resume_header_contact_info: "Paris | imadzairig@gmail.com"
resume_header_intro: "<p>Je me spécialise sur Symfony et AWS . Ma mission est de concevoir des produits web élégants utilisés par des millions de personnes à travers le monde. Tout en étant un développeur certifié Symfony et un développeur certifié AWS, je m'assure de fournir des solutions de haute qualité en respectant les bonnes pratiques de développement.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/zairigimad"
  resume_twitter_url:           "https://twitter.com/zairigimad"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/zairigimad/"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
